# 垃圾代码, 蹲个大佬佬提PR改进QAQ
database:
  host: localhost
  port: 3306
  database: database
  user: root
  password: password
  ssl: false

# 不推荐在游戏中热匿名, 看接管Tab的游戏插件会不会更新PlayerList.
# 如果加入后PlayerList不会更新不建议打开, 会导致白名.
# 因此, 非lobbyMode时会默认屏蔽匿名指令
# 类型: true false autodetect
# AutoDetect 仅检测以下插件: SuperLobby, DeluxeHub, Akropolis
lobbyMode: autodetect
# 当然. 你要是不听劝, 想在游戏中匿名, 启用修改这个
forceNickCommandOnGame:
  enable: false
  # 不启用功能, 则提示玩家
  deniedMessage: "&c你只能在大厅使用该命令."

# 是否在/nick上使用书本和牌子GUI
# 默认也会注册/nickbookgui, 开启此项后使用/nick即执行/nickbookgui
bookGui: true

# 是否启用ActionBar
actionbar:
  enable: true
  # 是否启用单独的隐身ActionBar
  # 需要匿名权限, 且玩家需要带有Meta "vanished"进行识别.
  vanishbar: true

messages:
  no_permission: "&c你没有使用该命令的权限!"
  player_only: "&c只有玩家才能使用该命令."
  usage_prefix: "&c用法: "
  # = usage_prefix + usage_main
  usage_main: "&c/nick [匿名] <前缀> <后缀>"
  
  actionbar_in_nick: "&f你目前&c已匿名"
  # = actionbar_in_nick + actionbar_in_nick_append_only_game
  actionbar_in_nick_append_only_game: "(仅游戏)"
  # = action_bar_in_nick + actionbar_in_nick_append_only_game + actionbar_in_nick_append_invis
  actionbar_in_nick_append_invis: "&f, &c已隐身"
  # only invis
  actionbar_in_invis: "&f你目前&c已隐身"
  
  nick_successful: "&a你已完成昵称设置!"
  unnick_successful: "&a你的昵称已经重置!"
  
  nick_fail_as_self: "&c你不能设置与自己一样的昵称!"
  nick_fail_too_short: "&c你不能设置少于&e3&c个字符的昵称."
  nick_fail_too_long: "&c你不能设置多于&e16&c个字符的昵称."
  # 直接拼接到最后了, 懒得写Orz
  nick_fail_contains_special_char: "&c你只能设置带有这些符号的昵称: "
  nick_fail_player_name_known_message: "&c你设置的昵称与某玩家相同, 请选择其他昵称!"
  
  unnick_fail_already: "&c你还没有设置昵称."