# 垃圾代码, 蹲个大佬佬提PR改进QAQ
database:
  host: localhost
  port: 3306
  database: database
  user: root
  password: password
  ssl: false

# 不推荐在游戏中热匿名, 具体情况看接管PlayerList/PlayerTag的插件会不会更新.
# 如果加入后PlayerList/PlayerTag不会更新不建议热匿名, 会导致白名.
# 因此, 非lobbyMode时会默认屏蔽匿名指令
# 类型: true false autodetect
# AutoDetect 仅检测以下插件: SuperLobby, DeluxeHub, Akropolis
lobbyMode: autodetect
# 当然. 你要是不听劝, 想在游戏中匿名, 启用这个
forceNickCommandOnGame:
  enable: false
  # 不启用功能, 则提示玩家
  denyMessage: "&c你只能在大厅使用该命令."

# 是否在/nick上使用书本和牌子GUI
# 默认也会注册, 开启此项后使用/nick即执行/nickbookgui
bookGui: true

# 是否启用ActionBar
actionbar:
  enable: true
  # 是否启用单独的隐身ActionBar
  # 玩家需要匿名使用权限, 并且需要带有Meta "vanished"进行识别.
  vanishbar: true

# 最多支持8个, 谁家服务器有大于8个rank，其次我懒
# 注意: 这里不要特意修改成"双s符号". 因为prefix是通过指令传递的, 使用可能会被移出服务器.
ranks:
  rank1:
    name: "&7默认"
    prefix: '&7'
    permission: ""
  rank2:
    name: "&aVIP"
    prefix: '&a[VIP] &a'
    permission: ""
  rank3:
    name: "&aVIP&6+"
    prefix: '&a[VIP&6+&a] &a'
    permission: ""
  rank4:
    name: "&bMVP"
    prefix: '&b[MVP&b] &b'
    permission: ""
  rank5:
    name: "&bMVP&c+"
    prefix: '&b[MVP&c+&b] &b'
    permission: ""

# %nl%为换行
messages:
  no_permission: "&c你没有使用该命令的权限!"
  player_only: "&c只有玩家才能使用该命令."
  usage_prefix: "&c用法: "
  # = usage_prefix + usage_main
  usage_main: "&c/nick [匿名] <前缀> <后缀>"
  notify: "&b<nickname>&f为&a<playername>&f的匿名."
  
  actionbar_in_nick: "&f你目前&c已匿名"
  # = actionbar_in_nick + actionbar_in_nick_append_only_game
  actionbar_in_nick_append_only_game: "(仅游戏)"
  # = action_bar_in_nick + actionbar_in_nick_append_only_game + actionbar_in_nick_append_invis
  actionbar_in_nick_append_invis: "&f, &c已隐身"
  # only invis
  actionbar_in_invis: "&f你目前&c已隐身"
  
  nick_successful: "&a你已完成匿名设置!"
  unnick_successful: "&a你的匿名已经重置!"
  
  nick_fail_as_self: "&c你不能设置与自己一样的匿名!"
  nick_fail_too_short: "&c你不能设置少于&e3&c个字符的匿名."
  nick_fail_too_long: "&c你不能设置多于&e16&c个字符的匿名."
  # 直接拼接到最后了, 懒得写Orz
  nick_fail_contains_special_char: "&c你只能设置带有这些符号的匿名: "
  nick_fail_player_name_known_message: "&c你设置的匿名与某玩家相同, 请选择其他匿名!"
  
  unnick_fail_already: "&c你还没有设置匿名."

  book:
    warning: "&0设置匿名将允许你使用不同的用户名进行游戏, 以避免被他人认出.%nl%%nl%所有规则仍然适用, 你仍可以被人工举报&m并且所有的匿名将会被记录&0.%nl%%nl%"
    warning_iknow: "&0➤ &n我已知晓, 开始设置匿名."
    warning_iknow_hover: "点此开始"

    ranktext: "帮助你设置匿名!%nl%首先, 你需要选择你想要显示的&l会员等级.%nl%%nl%"
    ranks: "&0➤ %rank%%nl%"
    ranks_hover: "点击这里, 显示为%rank%"

    nickname: "现在, 请选择你要使用的&0&l匿名!%nl%%nl%"
    nickname_inputname: "&0➤ &0输入匿名%nl%"
    nickname_inputname_hover: "点击这里, 输入你要使用的匿名"
    nickname_error_in_nickname: "&c&l在匿名时发生了一个问题, 请更换匿名后重试: "

    nick_finish: "&0你已完成匿名设置!%nl%%nl%你的匿名是: %nickedname%.%nl%%nl%要想恢复默认状态, 请使用: &l/nick reset"

