database:
  host: localhost
  port: 3306
  database: database
  user: root
  password: password
  ssl: false

lobbyMode: autodetect
# true, false, autodetect
# AutoDetect Only Support: SuperLobby, DeluxeHub, Akropolis